### PR TITLE
add three config features and one gnereral change

### PR DESCRIPTION
**Pull request by hoijui**
This is an enhancement or feature.

See the commit messages for details.

### CODE REVIEW

**Comment by mpdeimos** [comment]
I'd also prefer having the links stretching over thumbnails. But by looking at the diff, I think the produced HTML is invalid (`a`-tag opened within `h3`, but closed after).

As a project owner I'd also prefer separate pull requests (to separate concerns & discussions), dunno how @mmistakes handles this, tho ;)

**Comment by mmistakes** [comment]
@mpdeimos I pushed a small change to [make the entire entry in list or grid view a link](https://github.com/mmistakes/so-simple-theme/commit/7ea8b61bbfa95df815290e4cb53b7dd87186dbef). Unlike what this pull request proposes, there is no change to the HTML or layout files. I've used a little CSS magic to spread the entry's link to cover it's title, excerpt, meta info, and image (if used in grid view).

You can see it working on the demo site.
- [list view](https://mmistakes.github.io/so-simple-theme/)
- [grid view](https://mmistakes.github.io/so-simple-theme/recipes/)

image

image

**Comment by mpdeimos** [comment]
nice :+1:

**Comment by hoijui** [comment]
nice @mmistakes !
and thanks @mpdeimos ; I made 3 separate pull requests out of the still relevant commits, so this is not relevant anymore.

**Comment by mpdeimos** [comment]
@mmistakes I think there is a small glitch with your solution when it comes to link posts that I'm not sure whether it's intended. The expanded clickable anchor corresponds to the link to the post (entry.url) which is provided by the arrow symbol at the end, and not the external link (entry.link) which is provided by the text.

See: https://mmistakes.github.io/so-simple-theme/tags/#link

I'm not sure if it should be the other way round. Honestly I haven't noticed that the arrow points to something else until now, which is a bit confusing anyways.

**Comment by mmistakes** [comment]
This is the intended behavior. It follows the pattern used by popular "link bloggers". Post title links to the external source, while the icon becomes the post's permalink and links to entry.url

**Comment by mpdeimos** [comment]
Alright 👍

**Pull request closed without merging**
