### PR TITLE
Disable atom feed footer_link by default.

### PR DESCRIPTION
**Pull request by cyberang3l**
I want to remove the RSS feed, but since it is defined in the _config.yml of the theme this was not possible.

### CODE REVIEW

**Comment by mmistakes** [comment]
Feed can be easily disabled by modifying your own copy of _comfig.yml as you’ve done in the PR.

The config file bundled in the theme is a starter with some sensible defaults set. Closing for this reason.

**Comment by cyberang3l** [comment]
Yes, but if one wants no footer_links at all (so my own copy of _config.yml has no footer_links section), then it is not possible to get rid of the feed icon in the footer.

**Comment by mmistakes** [comment]
Then one simple adds `footer_links: false` to their `_config.yml` and it disables the links.

The relevant code is in [`_includes/footer.html`](https://github.com/mmistakes/so-simple-theme/blob/master/_includes/footer.html#L4-L15) if you want to see how that conditional works.

**Comment by cyberang3l** [comment]
Maybe this bit of information should be added in the documentation then?

**Pull request closed without merging**
