### PR TITLE
Attributing the post to multiple authors

### PR DESCRIPTION
**Pull request by yansh**
Added the possibility to have multiple authors on a single post by adding:

authors: 
-  Name 1
-  Name 2

without specifying authors the post will be attribute to the owner

### CODE REVIEW

**Comment by mmistakes** [comment]
This approach isn't all that DRY and has a lot of repeated code. Take a look at my other theme to see how I handled the [Liquid code for multiple authors](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/_author-bio.html). Essentially you use something like

```
{% if page.author %}
  {% assign author = site.data.authors[page.author] %}{% else %}{% assign author = site.owner %}
{% endif %}
```

Then you don't have to repeat author avatar, name, and link markup twice in if/else statements. It's far less error prone too.

**Comment by yansh** [comment]
@mmistakes I changed the code, but couldn't remove the repeated code. It's needed to support the case where page.author is not declared and falls back to site.owner. One way to avoid this is to initialize a collection within he Liquid code, which I think is impossible if the items are not string.

Your code assigns the post to a different author, I was going towards assigning the post to multiple users.

**Comment by mmistakes** [comment]
In that case I'm going to hold off merging. I prefer to keep things simple,
hence the name of the blog.

Didplaying multiple authors per posts seems like something only a few might
have use for and doesn't really need to be part of the theme.

Overriding a site wide author on a given post makes sense to me which is
why I included it in some of my other themes.

Also including a for loop to capture multiple authors can really add some
generation time to a site when you have a ton of posts. I'd hate to impact
those who have no need for the feature by increasing the amount of time it
takes to `jekyll build`.

**Comment by yansh** [comment]
Sure, no worries.

**Pull request closed without merging**
