### PR TITLE
Update disqus code to the updated embedded code

### PR DESCRIPTION
**Pull request by evanderkoogh**
Disqus has updated their embed code to make it a bit smaller and reduce the change of creating multiple threads per URL. The blog post announcing it can be found here: http://blog.disqus.com/post/131581805720/improve-your-disqus-integration-with-our-updated

### CODE REVIEW

**Comment by geyslan** [comment]
Hi, I applied this patch in my blog and now some posts are not showing the disqus correctly:

http://hackingbits.github.io/blog/cv-in-assembly-why-not/
http://hackingbits.github.io/articles/moedas-criptograficas-eletrons-como/

But some are showing ok:

http://hackingbits.github.io/blog/markdown-blog-writers-using-emacs/
http://hackingbits.github.io/blog/finding-out-the-current-in-use-xserver/

**Comment by mmistakes** [comment]
From my understanding, by default Disqus links comments by a page's URL. The point of the new embed is to set the page URL directly in their script along with the a unique ID.

My guess is it's the `page.identifier` line that's causing problems. It's probably doesn't match what Disqus has in their DB and isn't associating old comments for those pages correctly.

I've tried to use the unique page ID before and could never find a good way of generating it (see #69). The way @evanderkoogh did it isn't really providing a unique ID since it's just using the `page.id` which gives you something like `/2008/12/14/my-post`. If the page/post filename or permalink changes so will this ID. And that really shouldn't ever happen if you want this to work as intended.

I would just omit this line `+        this.page.identifier = '{{ page.id }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable` and see if your comments show up.

The only benefit of setting a unique `page.identifier` is if you ever move to a new domain, change permalinks, URLs, etc. It just saves you from using Disqus' migration tools to update URLs so comments link to the correct page.

**Comment by geyslan** [comment]
None.

I'll revert to old disqus indeed.

2015-11-02 11:31 GMT-03:00 Michael Rose <notifications@github.com>:

> From my understanding, by default Disqus links comments by a page's URL.
> The point of the new embed is to set the page URL directly in their script
> along with the a unique ID.
>
> My guess is it's the page.identifier line that's causing problems. It's
> probably doesn't match what Disqus has in their DB and isn't associating
> old comments for those pages correctly.
>
> I've tried to use the unique page ID before and could never find a good
> way of generating it (see #69
> <https://github.com/mmistakes/so-simple-theme/pull/69>). The way
> @evanderkoogh <https://github.com/evanderkoogh> did it isn't really
> providing a unique ID since it's just using the page.id which gives you
> something like /2008/12/14/my-post. If the page/post filename or
> permalink changes so will this ID. And that really shouldn't ever happen if
> you want this to work as intended.
>
> I would just omit this line + this.page.identifier = '{{ page.id }}'; //
> Replace PAGE_IDENTIFIER with your page's unique identifier variable and
> see if your comments show up.
>
> The only benefit of setting a unique page.identifier is if you ever move
> to a new domain, change permalinks, URLs, etc. It just saves you from using
> Disqus' migration tools to update URLs so comments link to the correct page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mmistakes/so-simple-theme/pull/176#issuecomment-153032047>
> .
>



-- 
Regards,

Geyslan G. Bem
hackingbits.com

**Comment by mmistakes** [comment]
@geyslan If its not broken don't fix it. Until I see the old embed breaking on my sites I'm not bothering updating. I use a customized version of the embed anyways to load comments only after tapping a "view more comments' button. Keeps page speed in check.

**Comment by geyslan** [comment]
@michael, you're right. Tks.

2015-11-02 12:22 GMT-03:00 Michael Rose <notifications@github.com>:

> @geyslan <https://github.com/geyslan> If its not broken don't fix it.
> Until I see the old embed breaking on my sites I'm not bothering updating.
> I use a customized version of the embed anyways to load comments only after
> tapping a "view more comments' button. Keeps page speed in check.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mmistakes/so-simple-theme/pull/176#issuecomment-153051133>
> .
>



-- 
Regards,

Geyslan G. Bem
hackingbits.com

**Comment by evanderkoogh** [comment]
Ah yes of course. It works great for me because I don't have any old comments on this new site. Probably best to reject the PR for now indeed.

**Pull request closed without merging**
